// <auto-generated />
using System;
using EuroLeaguesScore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuroLeaguesScore.Data.Migrations
{
    [DbContext(typeof(EuroLeaguesScoreDbContext))]
    [Migration("20260413195551_InitialCreateAndSeedDb")]
    partial class InitialCreateAndSeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Premier League"
                        },
                        new
                        {
                            Id = 2,
                            Name = "La Liga"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bundesliga"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Serie A"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ligue 1"
                        });
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamGoals")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamGoals")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            Assists = 0,
                            Goals = 0,
                            Name = "Erling Haaland",
                            Position = 4,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            Assists = 0,
                            Goals = 0,
                            Name = "Kevin De Bruyne",
                            Position = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            Assists = 0,
                            Goals = 0,
                            Name = "Phil Foden",
                            Position = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            Assists = 0,
                            Goals = 0,
                            Name = "Bukayo Saka",
                            Position = 4,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 25,
                            Assists = 0,
                            Goals = 0,
                            Name = "Martin Odegaard",
                            Position = 3,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Age = 27,
                            Assists = 0,
                            Goals = 0,
                            Name = "Gabriel Jesus",
                            Position = 4,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Age = 31,
                            Assists = 0,
                            Goals = 0,
                            Name = "Mohamed Salah",
                            Position = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            Age = 24,
                            Assists = 0,
                            Goals = 0,
                            Name = "Darwin Nunez",
                            Position = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Age = 25,
                            Assists = 0,
                            Goals = 0,
                            Name = "Trent Alexander-Arnold",
                            Position = 2,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 10,
                            Age = 21,
                            Assists = 0,
                            Goals = 0,
                            Name = "Jude Bellingham",
                            Position = 3,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 11,
                            Age = 23,
                            Assists = 0,
                            Goals = 0,
                            Name = "Vinicius Jr",
                            Position = 4,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 12,
                            Age = 23,
                            Assists = 0,
                            Goals = 0,
                            Name = "Rodrygo",
                            Position = 4,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 13,
                            Age = 35,
                            Assists = 0,
                            Goals = 0,
                            Name = "Robert Lewandowski",
                            Position = 4,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 14,
                            Age = 21,
                            Assists = 0,
                            Goals = 0,
                            Name = "Pedri",
                            Position = 3,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 15,
                            Age = 19,
                            Assists = 0,
                            Goals = 0,
                            Name = "Gavi",
                            Position = 3,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 16,
                            Age = 30,
                            Assists = 0,
                            Goals = 0,
                            Name = "Harry Kane",
                            Position = 4,
                            TeamId = 11
                        },
                        new
                        {
                            Id = 17,
                            Age = 21,
                            Assists = 0,
                            Goals = 0,
                            Name = "Jamal Musiala",
                            Position = 3,
                            TeamId = 11
                        },
                        new
                        {
                            Id = 18,
                            Age = 28,
                            Assists = 0,
                            Goals = 0,
                            Name = "Leroy Sane",
                            Position = 4,
                            TeamId = 11
                        },
                        new
                        {
                            Id = 19,
                            Age = 34,
                            Assists = 0,
                            Goals = 0,
                            Name = "Marco Reus",
                            Position = 3,
                            TeamId = 12
                        },
                        new
                        {
                            Id = 20,
                            Age = 22,
                            Assists = 0,
                            Goals = 0,
                            Name = "Karim Adeyemi",
                            Position = 4,
                            TeamId = 12
                        },
                        new
                        {
                            Id = 21,
                            Age = 27,
                            Assists = 0,
                            Goals = 0,
                            Name = "Julian Brandt",
                            Position = 3,
                            TeamId = 12
                        },
                        new
                        {
                            Id = 22,
                            Age = 24,
                            Assists = 0,
                            Goals = 0,
                            Name = "Dusan Vlahovic",
                            Position = 4,
                            TeamId = 16
                        },
                        new
                        {
                            Id = 23,
                            Age = 26,
                            Assists = 0,
                            Goals = 0,
                            Name = "Federico Chiesa",
                            Position = 4,
                            TeamId = 16
                        },
                        new
                        {
                            Id = 24,
                            Age = 29,
                            Assists = 0,
                            Goals = 0,
                            Name = "Adrien Rabiot",
                            Position = 3,
                            TeamId = 16
                        },
                        new
                        {
                            Id = 25,
                            Age = 26,
                            Assists = 0,
                            Goals = 0,
                            Name = "Lautaro Martinez",
                            Position = 4,
                            TeamId = 18
                        },
                        new
                        {
                            Id = 26,
                            Age = 27,
                            Assists = 0,
                            Goals = 0,
                            Name = "Nicolo Barella",
                            Position = 3,
                            TeamId = 18
                        },
                        new
                        {
                            Id = 27,
                            Age = 26,
                            Assists = 0,
                            Goals = 0,
                            Name = "Marcus Thuram",
                            Position = 4,
                            TeamId = 18
                        },
                        new
                        {
                            Id = 28,
                            Age = 25,
                            Assists = 0,
                            Goals = 0,
                            Name = "Kylian Mbappe",
                            Position = 4,
                            TeamId = 21
                        },
                        new
                        {
                            Id = 29,
                            Age = 27,
                            Assists = 0,
                            Goals = 0,
                            Name = "Ousmane Dembele",
                            Position = 4,
                            TeamId = 21
                        },
                        new
                        {
                            Id = 30,
                            Age = 24,
                            Assists = 0,
                            Goals = 0,
                            Name = "Vitinha",
                            Position = 3,
                            TeamId = 21
                        });
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("nvarchar(56)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Manchester",
                            Country = "England",
                            Draws = 0,
                            LeagueId = 1,
                            Losses = 0,
                            Name = "Manchester City",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            City = "London",
                            Country = "England",
                            Draws = 0,
                            LeagueId = 1,
                            Losses = 0,
                            Name = "Arsenal",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            City = "Liverpool",
                            Country = "England",
                            Draws = 0,
                            LeagueId = 1,
                            Losses = 0,
                            Name = "Liverpool",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            City = "Manchester",
                            Country = "England",
                            Draws = 0,
                            LeagueId = 1,
                            Losses = 0,
                            Name = "Manchester United",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            City = "London",
                            Country = "England",
                            Draws = 0,
                            LeagueId = 1,
                            Losses = 0,
                            Name = "Chelsea",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            City = "Madrid",
                            Country = "Spain",
                            Draws = 0,
                            LeagueId = 2,
                            Losses = 0,
                            Name = "Real Madrid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            City = "Barcelona",
                            Country = "Spain",
                            Draws = 0,
                            LeagueId = 2,
                            Losses = 0,
                            Name = "Barcelona",
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            City = "Madrid",
                            Country = "Spain",
                            Draws = 0,
                            LeagueId = 2,
                            Losses = 0,
                            Name = "Atletico Madrid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            City = "Seville",
                            Country = "Spain",
                            Draws = 0,
                            LeagueId = 2,
                            Losses = 0,
                            Name = "Sevilla",
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            City = "San Sebastian",
                            Country = "Spain",
                            Draws = 0,
                            LeagueId = 2,
                            Losses = 0,
                            Name = "Real Sociedad",
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            City = "Munich",
                            Country = "Germany",
                            Draws = 0,
                            LeagueId = 3,
                            Losses = 0,
                            Name = "Bayern Munich",
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            City = "Dortmund",
                            Country = "Germany",
                            Draws = 0,
                            LeagueId = 3,
                            Losses = 0,
                            Name = "Borussia Dortmund",
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            City = "Leipzig",
                            Country = "Germany",
                            Draws = 0,
                            LeagueId = 3,
                            Losses = 0,
                            Name = "RB Leipzig",
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            City = "Leverkusen",
                            Country = "Germany",
                            Draws = 0,
                            LeagueId = 3,
                            Losses = 0,
                            Name = "Bayer Leverkusen",
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            City = "Wolfsburg",
                            Country = "Germany",
                            Draws = 0,
                            LeagueId = 3,
                            Losses = 0,
                            Name = "Wolfsburg",
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            City = "Turin",
                            Country = "Italy",
                            Draws = 0,
                            LeagueId = 4,
                            Losses = 0,
                            Name = "Juventus",
                            Wins = 0
                        },
                        new
                        {
                            Id = 17,
                            City = "Milan",
                            Country = "Italy",
                            Draws = 0,
                            LeagueId = 4,
                            Losses = 0,
                            Name = "AC Milan",
                            Wins = 0
                        },
                        new
                        {
                            Id = 18,
                            City = "Milan",
                            Country = "Italy",
                            Draws = 0,
                            LeagueId = 4,
                            Losses = 0,
                            Name = "Inter Milan",
                            Wins = 0
                        },
                        new
                        {
                            Id = 19,
                            City = "Naples",
                            Country = "Italy",
                            Draws = 0,
                            LeagueId = 4,
                            Losses = 0,
                            Name = "Napoli",
                            Wins = 0
                        },
                        new
                        {
                            Id = 20,
                            City = "Rome",
                            Country = "Italy",
                            Draws = 0,
                            LeagueId = 4,
                            Losses = 0,
                            Name = "Roma",
                            Wins = 0
                        },
                        new
                        {
                            Id = 21,
                            City = "Paris",
                            Country = "France",
                            Draws = 0,
                            LeagueId = 5,
                            Losses = 0,
                            Name = "Paris Saint-Germain",
                            Wins = 0
                        },
                        new
                        {
                            Id = 22,
                            City = "Marseille",
                            Country = "France",
                            Draws = 0,
                            LeagueId = 5,
                            Losses = 0,
                            Name = "Marseille",
                            Wins = 0
                        },
                        new
                        {
                            Id = 23,
                            City = "Lyon",
                            Country = "France",
                            Draws = 0,
                            LeagueId = 5,
                            Losses = 0,
                            Name = "Lyon",
                            Wins = 0
                        },
                        new
                        {
                            Id = 24,
                            City = "Monaco",
                            Country = "Monaco",
                            Draws = 0,
                            LeagueId = 5,
                            Losses = 0,
                            Name = "Monaco",
                            Wins = 0
                        },
                        new
                        {
                            Id = 25,
                            City = "Lille",
                            Country = "France",
                            Draws = 0,
                            LeagueId = 5,
                            Losses = 0,
                            Name = "Lille",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Manager", b =>
                {
                    b.HasOne("EuroLeaguesScore.Data.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Match", b =>
                {
                    b.HasOne("EuroLeaguesScore.Data.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuroLeaguesScore.Data.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Player", b =>
                {
                    b.HasOne("EuroLeaguesScore.Data.Models.Manager", "Manager")
                        .WithMany("Players")
                        .HasForeignKey("ManagerId");

                    b.HasOne("EuroLeaguesScore.Data.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Team", b =>
                {
                    b.HasOne("EuroLeaguesScore.Data.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuroLeaguesScore.Data.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("League");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Manager", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("EuroLeaguesScore.Data.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
